// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

void* winrt_make_HV3DMRPCM_CHV3DMRPCM()
{
    return winrt::detach_abi(winrt::make<winrt::HV3DMRPCM::factory_implementation::CHV3DMRPCM>());
}
WINRT_EXPORT namespace winrt::HV3DMRPCM
{
    CHV3DMRPCM::CHV3DMRPCM() :
        CHV3DMRPCM(make<HV3DMRPCM::implementation::CHV3DMRPCM>())
    {
    }
}
