// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#ifndef WINRT_HV3DDUALITY_1_H
#define WINRT_HV3DDUALITY_1_H
#include "winrt/impl/HV3DDUALITY.0.h"
WINRT_EXPORT namespace winrt::HV3DDUALITY
{
    struct __declspec(empty_bases) IHV3DStartMenu :
        Windows::Foundation::IInspectable,
        impl::consume_t<IHV3DStartMenu>
    {
        IHV3DStartMenu(std::nullptr_t = nullptr) noexcept {}
        IHV3DStartMenu(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMainPage :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMainPage>
    {
        IMainPage(std::nullptr_t = nullptr) noexcept {}
        IMainPage(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
