// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#ifndef WINRT_HV3DDUALITY_0_H
#define WINRT_HV3DDUALITY_0_H
WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::HV3DDUALITY
{
    struct IHV3DStartMenu;
    struct IMainPage;
    struct HV3DStartMenu;
    struct MainPage;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<HV3DDUALITY::IHV3DStartMenu>{ using type = interface_category; };
    template <> struct category<HV3DDUALITY::IMainPage>{ using type = interface_category; };
    template <> struct category<HV3DDUALITY::HV3DStartMenu>{ using type = class_category; };
    template <> struct category<HV3DDUALITY::MainPage>{ using type = class_category; };
    template <> struct category<HV3DDUALITY::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<HV3DDUALITY::HV3DStartMenu> = L"HV3DDUALITY.HV3DStartMenu";
    template <> inline constexpr auto& name_v<HV3DDUALITY::MainPage> = L"HV3DDUALITY.MainPage";
    template <> inline constexpr auto& name_v<HV3DDUALITY::XamlMetaDataProvider> = L"HV3DDUALITY.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<HV3DDUALITY::IHV3DStartMenu> = L"HV3DDUALITY.IHV3DStartMenu";
    template <> inline constexpr auto& name_v<HV3DDUALITY::IMainPage> = L"HV3DDUALITY.IMainPage";
    template <> inline constexpr guid guid_v<HV3DDUALITY::IHV3DStartMenu>{ 0x2B5D6998,0x9192,0x57C7,{ 0xAA,0x14,0x5B,0x6C,0x62,0x1E,0xDC,0xB6 } }; // 2B5D6998-9192-57C7-AA14-5B6C621EDCB6
    template <> inline constexpr guid guid_v<HV3DDUALITY::IMainPage>{ 0xB68B9939,0xDDF2,0x56AA,{ 0xBB,0xDC,0xBB,0x25,0x4F,0xE3,0xE9,0xBD } }; // B68B9939-DDF2-56AA-BBDC-BB254FE3E9BD
    template <> struct default_interface<HV3DDUALITY::HV3DStartMenu>{ using type = HV3DDUALITY::IHV3DStartMenu; };
    template <> struct default_interface<HV3DDUALITY::MainPage>{ using type = HV3DDUALITY::IMainPage; };
    template <> struct default_interface<HV3DDUALITY::XamlMetaDataProvider>{ using type = Windows::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<HV3DDUALITY::IHV3DStartMenu>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <> struct abi<HV3DDUALITY::IMainPage>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_HV3DDUALITY_IHV3DStartMenu
    {
        [[nodiscard]] WINRT_IMPL_AUTO(int32_t) MyProperty() const;
        WINRT_IMPL_AUTO(void) MyProperty(int32_t value) const;
    };
    template <> struct consume<HV3DDUALITY::IHV3DStartMenu>
    {
        template <typename D> using type = consume_HV3DDUALITY_IHV3DStartMenu<D>;
    };
    template <typename D>
    struct consume_HV3DDUALITY_IMainPage
    {
        [[nodiscard]] WINRT_IMPL_AUTO(int32_t) MyProperty() const;
        WINRT_IMPL_AUTO(void) MyProperty(int32_t value) const;
    };
    template <> struct consume<HV3DDUALITY::IMainPage>
    {
        template <typename D> using type = consume_HV3DDUALITY_IMainPage<D>;
    };
}
#endif
