// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#ifndef WINRT_HV3DMPU_1_H
#define WINRT_HV3DMPU_1_H
#include "winrt/impl/HV3DMPU.0.h"
WINRT_EXPORT namespace winrt::HV3DMPU
{
    struct __declspec(empty_bases) ICHV3DMPU :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICHV3DMPU>
    {
        ICHV3DMPU(std::nullptr_t = nullptr) noexcept {}
        ICHV3DMPU(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
