// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#ifndef WINRT_HV3DMPU_2_H
#define WINRT_HV3DMPU_2_H
#include "winrt/impl/HV3DMPU.1.h"
WINRT_EXPORT namespace winrt::HV3DMPU
{
    struct __declspec(empty_bases) CHV3DMPU : HV3DMPU::ICHV3DMPU
    {
        CHV3DMPU(std::nullptr_t) noexcept {}
        CHV3DMPU(void* ptr, take_ownership_from_abi_t) noexcept : HV3DMPU::ICHV3DMPU(ptr, take_ownership_from_abi) {}
        CHV3DMPU();
    };
}
#endif
