// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

void* winrt_make_HV3DMYSQLSTD_CHV3DMYSQLSTD()
{
    return winrt::detach_abi(winrt::make<winrt::HV3DMYSQLSTD::factory_implementation::CHV3DMYSQLSTD>());
}
WINRT_EXPORT namespace winrt::HV3DMYSQLSTD
{
    CHV3DMYSQLSTD::CHV3DMYSQLSTD() :
        CHV3DMYSQLSTD(make<HV3DMYSQLSTD::implementation::CHV3DMYSQLSTD>())
    {
    }
}
