// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#ifndef WINRT_HV3DDUALITY_H
#define WINRT_HV3DDUALITY_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.200729.8"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.200729.8"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.2.h"
#include "winrt/impl/HV3DDUALITY.2.h"
namespace winrt::impl
{
    template <typename D> WINRT_IMPL_AUTO(int32_t) consume_HV3DDUALITY_IHV3DStartMenu<D>::MyProperty() const
    {
        int32_t value{};
        check_hresult(WINRT_IMPL_SHIM(HV3DDUALITY::IHV3DStartMenu)->get_MyProperty(&value));
        return value;
    }
    template <typename D> WINRT_IMPL_AUTO(void) consume_HV3DDUALITY_IHV3DStartMenu<D>::MyProperty(int32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(HV3DDUALITY::IHV3DStartMenu)->put_MyProperty(value));
    }
    template <typename D> WINRT_IMPL_AUTO(int32_t) consume_HV3DDUALITY_IMainPage<D>::MyProperty() const
    {
        int32_t value{};
        check_hresult(WINRT_IMPL_SHIM(HV3DDUALITY::IMainPage)->get_MyProperty(&value));
        return value;
    }
    template <typename D> WINRT_IMPL_AUTO(void) consume_HV3DDUALITY_IMainPage<D>::MyProperty(int32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(HV3DDUALITY::IMainPage)->put_MyProperty(value));
    }
    template <typename D>
    struct produce<D, HV3DDUALITY::IHV3DStartMenu> : produce_base<D, HV3DDUALITY::IHV3DStartMenu>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
    template <typename D>
    struct produce<D, HV3DDUALITY::IMainPage> : produce_base<D, HV3DDUALITY::IMainPage>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::HV3DDUALITY
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::HV3DDUALITY::IHV3DStartMenu> : winrt::impl::hash_base {};
    template<> struct hash<winrt::HV3DDUALITY::IMainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::HV3DDUALITY::HV3DStartMenu> : winrt::impl::hash_base {};
    template<> struct hash<winrt::HV3DDUALITY::MainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::HV3DDUALITY::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
}
#endif
