// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#ifndef WINRT_HV3DMYSQLSTD_H
#define WINRT_HV3DMYSQLSTD_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.200729.8"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.200729.8"
#include "winrt/impl/HV3DMYSQLSTD.2.h"
namespace winrt::impl
{
    template <typename D> WINRT_IMPL_AUTO(int32_t) consume_HV3DMYSQLSTD_ICHV3DMYSQLSTD<D>::MyProperty() const
    {
        int32_t value{};
        check_hresult(WINRT_IMPL_SHIM(HV3DMYSQLSTD::ICHV3DMYSQLSTD)->get_MyProperty(&value));
        return value;
    }
    template <typename D> WINRT_IMPL_AUTO(void) consume_HV3DMYSQLSTD_ICHV3DMYSQLSTD<D>::MyProperty(int32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(HV3DMYSQLSTD::ICHV3DMYSQLSTD)->put_MyProperty(value));
    }
    template <typename D>
    struct produce<D, HV3DMYSQLSTD::ICHV3DMYSQLSTD> : produce_base<D, HV3DMYSQLSTD::ICHV3DMYSQLSTD>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::HV3DMYSQLSTD
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::HV3DMYSQLSTD::ICHV3DMYSQLSTD> : winrt::impl::hash_base {};
    template<> struct hash<winrt::HV3DMYSQLSTD::CHV3DMYSQLSTD> : winrt::impl::hash_base {};
#endif
}
#endif
