// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#ifndef WINRT_HV3DMYSQLSTD_2_H
#define WINRT_HV3DMYSQLSTD_2_H
#include "winrt/impl/HV3DMYSQLSTD.1.h"
WINRT_EXPORT namespace winrt::HV3DMYSQLSTD
{
    struct __declspec(empty_bases) CHV3DMYSQLSTD : HV3DMYSQLSTD::ICHV3DMYSQLSTD
    {
        CHV3DMYSQLSTD(std::nullptr_t) noexcept {}
        CHV3DMYSQLSTD(void* ptr, take_ownership_from_abi_t) noexcept : HV3DMYSQLSTD::ICHV3DMYSQLSTD(ptr, take_ownership_from_abi) {}
        CHV3DMYSQLSTD();
    };
}
#endif
