#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class Image;
                ref class TextBlock;
                ref class Button;
            }
        }
    }
}

namespace HV3DDUALITY
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class HV3DStartMenu : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class HV3DStartMenu_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ StartMenu;
        private: ::Windows::UI::Xaml::Controls::Image^ RightBanner;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ NewProject;
        private: ::Windows::UI::Xaml::Controls::Button^ NewEmptyProject;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LoadProject;
        private: ::Windows::UI::Xaml::Controls::Image^ LeftBanner;
    };
}

