// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

void* winrt_make_HV3DDUALITY_HV3DStartMenu()
{
    return winrt::detach_abi(winrt::make<winrt::HV3DDUALITY::factory_implementation::HV3DStartMenu>());
}
WINRT_EXPORT namespace winrt::HV3DDUALITY
{
    HV3DStartMenu::HV3DStartMenu() :
        HV3DStartMenu(make<HV3DDUALITY::implementation::HV3DStartMenu>())
    {
    }
}
