//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::HV3DDUALITY::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct HV3DStartMenuT : public ::winrt::HV3DDUALITY::implementation::HV3DStartMenu_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename HV3DStartMenuT::base_type;
        using base_type::base_type;
        using class_type = typename HV3DStartMenuT::class_type;

        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::Grid StartMenu()
        {
            return _StartMenu;
        }
        void StartMenu(::winrt::Windows::UI::Xaml::Controls::Grid value)
        {
            _StartMenu = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Image RightBanner()
        {
            return _RightBanner;
        }
        void RightBanner(::winrt::Windows::UI::Xaml::Controls::Image value)
        {
            _RightBanner = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock NewProject()
        {
            return _NewProject;
        }
        void NewProject(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _NewProject = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock LoadProject()
        {
            return _LoadProject;
        }
        void LoadProject(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _LoadProject = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Image LeftBanner()
        {
            return _LeftBanner;
        }
        void LeftBanner(::winrt::Windows::UI::Xaml::Controls::Image value)
        {
            _LeftBanner = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct HV3DStartMenu_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Controls::Grid _StartMenu{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Image _RightBanner{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _NewProject{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _LoadProject{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Image _LeftBanner{nullptr};
    };
}

