// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#pragma once
#include "winrt/HV3DDUALITY.h"
#include "winrt/Windows.UI.Xaml.Markup.h"
namespace winrt::HV3DDUALITY::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) XamlMetaDataProvider_base : implements<D, HV3DDUALITY::XamlMetaDataProvider, I...>
    {
        using base_type = XamlMetaDataProvider_base;
        using class_type = HV3DDUALITY::XamlMetaDataProvider;
        using implements_type = typename XamlMetaDataProvider_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"HV3DDUALITY.XamlMetaDataProvider";
        }
    };
}
namespace winrt::HV3DDUALITY::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) XamlMetaDataProviderT : implements<D, Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = HV3DDUALITY::XamlMetaDataProvider;

        hstring GetRuntimeClassName() const
        {
            return L"HV3DDUALITY.XamlMetaDataProvider";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_XAMLMETADATAPROVIDER_XAML_G_H) || __has_include("XamlMetaDataProvider.xaml.g.h")
#include "XamlMetaDataProvider.xaml.g.h"
#else

namespace winrt::HV3DDUALITY::implementation
{
    template <typename D, typename... I>
    using XamlMetaDataProviderT = XamlMetaDataProvider_base<D, I...>;
}

#endif
