// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

void* winrt_make_HV3DDUALITY_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::HV3DDUALITY::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::HV3DDUALITY
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<HV3DDUALITY::implementation::XamlMetaDataProvider>())
    {
    }
}
