// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#ifndef WINRT_HV3DMRPCM_1_H
#define WINRT_HV3DMRPCM_1_H
#include "winrt/impl/HV3DMRPCM.0.h"
WINRT_EXPORT namespace winrt::HV3DMRPCM
{
    struct __declspec(empty_bases) ICHV3DMRPCM :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICHV3DMRPCM>
    {
        ICHV3DMRPCM(std::nullptr_t = nullptr) noexcept {}
        ICHV3DMRPCM(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
