// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#ifndef WINRT_HV3DMRPCM_2_H
#define WINRT_HV3DMRPCM_2_H
#include "winrt/impl/HV3DMRPCM.1.h"
WINRT_EXPORT namespace winrt::HV3DMRPCM
{
    struct __declspec(empty_bases) CHV3DMRPCM : HV3DMRPCM::ICHV3DMRPCM
    {
        CHV3DMRPCM(std::nullptr_t) noexcept {}
        CHV3DMRPCM(void* ptr, take_ownership_from_abi_t) noexcept : HV3DMRPCM::ICHV3DMRPCM(ptr, take_ownership_from_abi) {}
        CHV3DMRPCM();
    };
}
#endif
