// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

void* winrt_make_HV3DMPU_CHV3DMPU()
{
    return winrt::detach_abi(winrt::make<winrt::HV3DMPU::factory_implementation::CHV3DMPU>());
}
WINRT_EXPORT namespace winrt::HV3DMPU
{
    CHV3DMPU::CHV3DMPU() :
        CHV3DMPU(make<HV3DMPU::implementation::CHV3DMPU>())
    {
    }
}
